steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/sharlayan/simc-internal:${BRANCH_NAME}-${SHORT_SHA}', '--build-arg', 'PTR_DATA=1', '.' ]

timeout: '5400s'
images:
  - 'gcr.io/sharlayan/simc-internal:${BRANCH_NAME}-${SHORT_SHA}'
options:
  machineType: 'N1_HIGHCPU_32'
