steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/sharlayan/simc-internal:${BRANCH_NAME}-${SHORT_SHA}', '--build-arg', 'PTR_DATA=1', '.' ]

timeout: '5400s'
images:
  - 'us-west2-docker.pkg.dev/sharlayan/simc-internal:${BRANCH_NAME}-${SHORT_SHA}'